### ISSUE TITLE
behave installed but still says "behave could not be found. Is it installed?"

### ISSUE THREAD

**Issue by the-shank** [mixxorz/BehaveToolkit#16]
I have behave installed on my system (OSX Yosemite, python 3.4.3). However in the ST3 console, I can see "Exception: behave could not be found. Is it installed?"

Browsing the code, I see the it does a `which('behave')` before throwing the exception. Running the `which('behave')` command manually gives me `/usr/local/bin/behave`. Pip list also confirms that behave is installed.

Can you please give any pointers as to how do I go about fixing this.

**Comment by mixxorz** [comment]
Honestly, the way this is currently implemented isn't the best. Does the same thing happen if you open Sublime Text from the command line using the `subl` command?

**Comment by the-shank** [comment]
Whoa ! It works fine when I launch Sublime text using the `subl` command.

**Comment by mixxorz** [comment]
I thought it would. Ugh. I really don't like the way I implemented this.

Just as a side note, you could have also specifically specified where behave is. Instructions [here](http://behavetoolkit.readthedocs.org/en/latest/configuration.html#behave-command).

I'm working to rewrite the way the whole plugin works. This would alleviate the need for behave to be installed plus a massive speed increase. Hopefully I get to that soon.

Anyway, closing this now. Glad I helped. :grinning:
